# Generated by Django 4.1.4 on 2023-01-03 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'db_table': 'artist',
            },
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('artista_musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.artista')),
            ],
            options={
                'verbose_name': 'Music',
                'verbose_name_plural': 'Musics',
                'db_table': 'music',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('playlist_musica', models.ManyToManyField(to='musica.musica')),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'playlists',
                'db_table': 'playlist',
            },
        ),
    ]
