# Generated by Django 4.1.4 on 2022-12-28 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='musica.musica')),
            ],
        ),
    ]
