# Generated by Django 4.1.4 on 2023-01-03 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musica',
            old_name='artista_musica',
            new_name='artista',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='playlist_musica',
            new_name='musicas',
        ),
    ]
