# Generated by Django 4.1.4 on 2023-01-03 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0002_rename_artista_musica_musica_artista_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='dt_criacao',
            new_name='_dt_criacao',
        ),
        migrations.RenameField(
            model_name='musica',
            old_name='dt_criacao',
            new_name='_dt_criacao',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='dt_criacao',
            new_name='_dt_criacao',
        ),
    ]
