# Generated by Django 4.1.4 on 2022-12-28 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0002_playlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
