# Generated by Django 4.1.4 on 2022-12-28 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0003_delete_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='musica.musica')),
            ],
        ),
    ]
