# Generated by Django 4.1.4 on 2022-12-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0004_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='musica',
        ),
        migrations.AddField(
            model_name='playlist',
            name='musica',
            field=models.ManyToManyField(to='musica.musica'),
        ),
    ]
